<a href="https://colab.research.google.com/github/ersjunior/3DTS-DataProcessingWithPython/blob/main/3DTS_Processamento_de_dados_com_Python_A2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Extrutura de Dados com Python

In [1]:
# Exemplo de lista e vetores de dados
notas = [6,7,9]
print(notas[0])
notas[0] = 6.5
print(notas[0])

6
6.5


In [2]:
# Exemplo de inserção de dados
notas.append(10)
print(notas)

[6.5, 7, 9, 10]


In [5]:
# Listas | Vetores e laços:
notas = [ 5,5,6,6,7,7,8,8,9,9]
soma = 0
for i in range(0, len(notas),1):
 soma = soma + notas[i]
media = soma/len(notas)
print(media)

7.0


In [7]:
# Lista | Vetores e laços 2:
notas = [ 5,5,6,6,7,7,8,8,9,9]
soma = 0
for n in notas:
 soma = soma + n
media = soma/len(notas)
print(media)

7.0


In [9]:
# Laços | Loops e Listas | Vetores
def media_turma():
    notas = [5,5,6,6,7,7,8,8,9,9]
    soma = 0
    for i in range (0,10,1):
        soma = soma + notas[i]
    return(soma/len(notas))


media = media_turma()
print(media)

7.0


In [11]:
# Listas: Slicing (fatiando)
listas = [1, 2, 3, 4, 5]

print(listas[1:1])
print(listas[1:3])
print(listas[1:-1])
print(listas[:2])

[]
[2, 3]
[2, 3, 4]
[1, 2]


In [13]:
# Exercícios: Listas/Vetores
"""
Encontre a maior nota da turma com notas: 7, 6, 9, 9, 8, 8, 10, 5, 6 e 7
"""
notas = [7, 6, 9, 9, 8, 8, 10, 5, 6, 7]
maior_nota = max(notas)
print("A maior nota da turma é:", maior_nota)


A maior nota da turma é: 10


# Tuplas com python

In [15]:
# Exercício: Tupla
"""
- Crie uma função que receba coordenadas de dois
pontos no plano e calcule a distância entre eles.
"""
import math

def calcular_distancia(ponto1, ponto2):
    x1, y1 = ponto1
    x2, y2 = ponto2

    distancia = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)
    return distancia

ponto1 = (2, 3)
ponto2 = (5, 7)

distancia = calcular_distancia(ponto1, ponto2)
print("A distância entre os pontos é:", distancia)

A distância entre os pontos é: 5.0


In [16]:
# Exercício: Tupla
"""
- Crie uma função similar mas que sejam dois
pontos no espaço tridimensional
"""
import math

def calcular_distancia_3d(ponto1, ponto2):
    x1, y1, z1 = ponto1
    x2, y2, z2 = ponto2

    distancia = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2 + (z2 - z1) ** 2)
    return distancia

ponto1 = (2, 3, 4)
ponto2 = (5, 7, 1)

distancia = calcular_distancia_3d(ponto1, ponto2)
print("A distância entre os pontos é:", distancia)

A distância entre os pontos é: 5.830951894845301


# Dicionários com Python

In [17]:
# Dicionários
"""
Dicionários assim como as listas e tuplas são para armazenar dados
porém um dicionário não é uma sequência de valores ordenados,
desse modo não podemos acessar esses dados por um índice como
fazemos em listas e tuplas.
"""
turma_dic = {
    "Eliezer": 10,
    "Junior": 9
}

"""
Para acessar os dados de um dicionário fazemos por meio de chaves
(nomes que iremos associar aos dados)
"""

print(turma_dic["Eliezer"])

10


In [18]:
# Dicionários: Remover elementos
"""
Para saber o tamanho usamos ainda len() e para demover del()
"""

print('Tamanho: ', len(turma_dic))

del turma_dic["Junior"]
print('Tamanho: ', len(turma_dic))
print(turma_dic)

Tamanho:  2
Tamanho:  1
{'Eliezer': 10}


In [19]:
# Laços/Loops e Listas/Vetores

def media_dicionario_turma(dic_turma):
    soma = 0
    for nome_aluno in dic_turma:
        nota_aluno = dic_turma[nome_aluno]
        soma = soma + nota_aluno
    return soma / len(dic_turma)

turma_dic = {
    "Eliézer": 10.0,
    "Junior": 5.0
}

mdt = media_dicionario_turma(turma_dic)
print(mdt)

7.5


In [20]:
# Laços/Loops e Listas/Vetores 2

def calc_media(notas):
    soma = 0
    for i in range(0, len(notas),1):
        soma = soma + notas[i]
    return soma / len(notas)

def notas_final(turma):
    soma = 0
    for nome_aluno in turma:
        notas_aluno = turma[nome_aluno]
        media_aluno = calc_media(notas_aluno)
        soma = soma + media_aluno
        print(nome_aluno +" "+ str(media_aluno))
    return soma / len(turma)

turma_final = {
    "Eliézer": [10.0, 9.0, 9.5],
    "Junior": [5.0, 7.5, 9.5]
}

mdt = notas_final(turma_final)
print('Media turma', mdt)

Eliézer 9.5
Junior 7.333333333333333
Media turma 8.416666666666666


# Numpy - Vetores e Arrays

In [21]:
# Usando vetores e arrays com numpy
import numpy as np

a1 = [1, 2, 3]
print(a1)

a2 = np.array([1, 2, 3])
print(a2)

[1, 2, 3]
[1 2 3]


In [22]:
# numpy: Matrizes (2D)
b = np.array([
    [1,2,3],[4,5,6]
])

print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [25]:
# Opção usual de acesso
print(b[1,1])

# Outra opção de acesso
print(b[1][1])

5
5


In [26]:
# numpy: Outras Inicializações 
zero2_2 = np.zeros((2,2))
print(zero2_2)

[[0. 0.]
 [0. 0.]]


In [27]:
ones3_3 = np.ones((3,3))
print(ones3_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# numpy: Slicing
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

print(a)

fatia = a[2:3,0:4]
print('FATIA')
print(fatia)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
FATIA
[[ 9 10 11 12]]


In [29]:
# numpy: Query
a = np.array([[1,2],
              [3,4],
              [5,6]])

print(a)
print(a[a>2])


[[1 2]
 [3 4]
 [5 6]]
[3 4 5 6]


In [30]:
# numpy: Soma (elemento a elemento)
x = np.array([1,2])
y = np.array([5,6])
z = x + y

print(z)

[6 8]


In [31]:
# numpy: Soma (elemento a elemento)
x = [1,2]
y = [5,6]
z = x + y

print(z)

[1, 2, 5, 6]


In [33]:
# numpy: Subtração (elemento a elemento)
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = x - y

print(z)

[[-4 -4]
 [-4 -4]]


In [34]:
# numpy: Divisão (elemento a elemento)
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = x / y

print(z)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [35]:
# numpy: Multiplicação (elemento a elemento)
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = x * y

print(z)

[[ 5 12]
 [21 32]]


In [37]:
# numpy: Multiplicação de MATRIZES
notas = np.array([
    [7,8,9],
    [5,6,7],
    [5,5,5],
    [9,9,9]
])

peso = np.array([
    [0.4],
    [0.4],
    [0.2]
])

medias = notas @ peso

print(notas)
print(notas.shape)
print()
print(peso)
print(peso.shape)
print()
print(medias)

[[7 8 9]
 [5 6 7]
 [5 5 5]
 [9 9 9]]
(4, 3)

[[0.4]
 [0.4]
 [0.2]]
(3, 1)

[[7.8]
 [5.8]
 [5. ]
 [9. ]]


In [42]:
# numpy: Transposta
notas_t = notas.T
print(notas_t)
print(notas_t.shape)
print()

peso_t = peso.T
print(peso_t)
print(peso_t.shape)
print()

medias = peso_t @ notas_t
print(medias)

[[7 5 5 9]
 [8 6 5 9]
 [9 7 5 9]]
(3, 4)

[[0.4 0.4 0.2]]
(1, 3)

[[7.8 5.8 5.  9. ]]


In [43]:
# numpy: Funções
"""
Diversas Funções, como:
• mean( ) # média
• std( ) # desvio padrão
• min( ) # mínimo
• max( ) # máximo
• sum( ) # soma
"""
media = medias.mean()
desv = medias.std()
menor = medias.min()
maior = medias.max()
soma = medias.sum()

print(media)
print(desv)
print(menor)
print(maior)
print(soma)

6.9
1.5842979517754858
5.0
9.0
27.6


# Exercícios - Finais

In [44]:
# Exercício 1:
"""
1) Escreva um programa que lê do teclado e registra em uma matriz (3x6), 
a receita de 3 (três) empresas do último semestre (6 meses). 
Após ler a receita de cada empresa mes a mes, seu programa deve então retornar a 
Média e o Desvio Padrão Populacional das receitas do semestre 
para cada uma das empresas.
"""
import numpy as np

# Inicializar a matriz de receitas
receitas = np.zeros((3, 6))

# Ler as receitas de cada empresa mês a mês
for i in range(3):
    print("Empresa", i+1)
    for j in range(6):
        receitas[i, j] = float(input("Digite a receita do mês {}: ".format(j+1)))

# Calcular a média e o desvio padrão populacional das receitas do semestre para cada empresa
medias = np.mean(receitas, axis=1)
desvios_padrao = np.std(receitas, axis=1, ddof=0)

# Imprimir os resultados
for i in range(3):
    print("Empresa", i+1)
    print("Média:", medias[i])
    print("Desvio padrão populacional:", desvios_padrao[i])
    print()

Empresa 1
Digite a receita do mês 1: 1200
Digite a receita do mês 2: 1300
Digite a receita do mês 3: 1500
Digite a receita do mês 4: 1100
Digite a receita do mês 5: 1200
Digite a receita do mês 6: 1400
Empresa 2
Digite a receita do mês 1: 2150
Digite a receita do mês 2: 2320
Digite a receita do mês 3: 2000
Digite a receita do mês 4: 2640
Digite a receita do mês 5: 2350
Digite a receita do mês 6: 2000
Empresa 3
Digite a receita do mês 1: 1780
Digite a receita do mês 2: 1910
Digite a receita do mês 3: 1870
Digite a receita do mês 4: 1650
Digite a receita do mês 5: 1800
Digite a receita do mês 6: 1900
Empresa 1
Média: 1283.3333333333333
Desvio padrão populacional: 134.37096247164249

Empresa 2
Média: 2243.3333333333335
Desvio padrão populacional: 224.25184255405546

Empresa 3
Média: 1818.3333333333333
Desvio padrão populacional: 89.33395522171598



In [45]:
# Exercício 2:
"""
2) Crie um programa no qual você deve ler do teclado todas as compras de 6 (seis) ações/ativos 
realizadas em um dia, coletando informações de preço e quantidade para cada uma. 
Armazene essa informação em uma matriz 1x6 com os preços. 
Já as quantidades armazenadas em uma outra matriz 6x1. De posse dessas duas informações 
realize o cálculo final do montante em dinheiro de ativos adquiridos neste dia para sua carteira.
"""
import numpy as np

# Ler os preços das ações
precos = np.zeros((1, 6))
for i in range(6):
    precos[0, i] = float(input("Digite o preço da ação {}: ".format(i+1)))

# Ler as quantidades das ações
quantidades = np.zeros((6, 1))
for i in range(6):
    quantidades[i, 0] = float(input("Digite a quantidade da ação {}: ".format(i+1)))

# Calcular o montante em dinheiro de ativos adquiridos
montante = np.dot(precos, quantidades)

# Imprimir o resultado
print("Montante em dinheiro de ativos adquiridos: R$", montante[0, 0])

Digite o preço da ação 1: 12.75
Digite o preço da ação 2: 15.97
Digite o preço da ação 3: 23.70
Digite o preço da ação 4: 1.20
Digite o preço da ação 5: 3.96
Digite o preço da ação 6: 8.97
Digite a quantidade da ação 1: 125
Digite a quantidade da ação 2: 89
Digite a quantidade da ação 3: 97
Digite a quantidade da ação 4: 350
Digite a quantidade da ação 5: 135
Digite a quantidade da ação 6: 20
Montante em dinheiro de ativos adquiridos: R$ 6447.98


In [47]:
# Exercício 3:
"""
3) Uma corretora que trabalha com 3 ativos principais VALE5, PETR4 e BBDC4, 
gostaria de registrar os rendimentos da semana em uma matriz 5x3. 
Crie um programa que lê do teclado dia-a-dia o rendimento de cada um dos 3 ativos. 
Em seguida o programa deve fazer o cálculo de rendimento acumulado de cada ativo na semana. 
E por fim, apresenta o rendimento médio total do fundo.
"""
import numpy as np

# Inicializar a matriz de rendimentos
rendimentos = np.zeros((5, 3))

# Ler os rendimentos de cada ativo dia-a-dia
for i in range(5):
    print("Dia", i+1)
    for j in range(3):
        rendimentos[i, j] = float(input("Digite o rendimento do ativo {}: ".format(j+1)))

# Calcular o rendimento acumulado de cada ativo na semana
rendimentos_acumulados = np.cumprod(1 + rendimentos, axis=0) - 1

# Calcular o rendimento médio total do fundo
rendimento_medio = np.mean(rendimentos)

# Imprimir os resultados
for j in range(3):
    print("Ativo", j+1)
    print("Rendimento acumulado na semana:", rendimentos_acumulados[-1, j])
    print()
print("Rendimento médio total do fundo:", rendimento_medio)

Dia 1
Digite o rendimento do ativo 1: 15
Digite o rendimento do ativo 2: 2
Digite o rendimento do ativo 3: 10
Dia 2
Digite o rendimento do ativo 1: 4
Digite o rendimento do ativo 2: 6
Digite o rendimento do ativo 3: 1
Dia 3
Digite o rendimento do ativo 1: 10
Digite o rendimento do ativo 2: 19
Digite o rendimento do ativo 3: 12
Dia 4
Digite o rendimento do ativo 1: 5
Digite o rendimento do ativo 2: 6
Digite o rendimento do ativo 3: 4
Dia 5
Digite o rendimento do ativo 1: 3
Digite o rendimento do ativo 2: 2
Digite o rendimento do ativo 3: 3
Ativo 1
Rendimento acumulado na semana: 21119.0

Ativo 2
Rendimento acumulado na semana: 8819.0

Ativo 3
Rendimento acumulado na semana: 5719.0

Rendimento médio total do fundo: 6.8


In [48]:
# Exercício 4:
"""
4) As 3 principais cidades brasileiras estão preocupadas com a taxa de ocupação de hospitais durante o COVID. 
Crie um programa que lê do teclado dia a dia para cada cidade e registra em uma matriz 7x3 a 
taxa de ocupação dos hospitais dessas 3 cidades nos última semana (7 dias). 
Seu programa deve apresentar então o mínimo, máximo e média de ocupação dos leitos para cada cidade.
"""
import numpy as np

# Inicializar a matriz de taxa de ocupação dos leitos
taxas_ocupacao = np.zeros((7, 3))

# Ler as taxas de ocupação dos leitos dia a dia para cada cidade
for i in range(7):
    print("Dia", i+1)
    for j in range(3):
        taxas_ocupacao[i, j] = float(input("Digite a taxa de ocupação da cidade {}: ".format(j+1)))

# Calcular o mínimo, máximo e média de ocupação dos leitos para cada cidade
minimos = np.min(taxas_ocupacao, axis=0)
maximos = np.max(taxas_ocupacao, axis=0)
medias = np.mean(taxas_ocupacao, axis=0)

# Imprimir os resultados
for j in range(3):
    print("Cidade", j+1)
    print("Mínimo de ocupação:", minimos[j])
    print("Máximo de ocupação:", maximos[j])
    print("Média de ocupação:", medias[j])
    print()

Dia 1
Digite a taxa de ocupação da cidade 1: 55000
Digite a taxa de ocupação da cidade 2: 30000
Digite a taxa de ocupação da cidade 3: 12000
Dia 2
Digite a taxa de ocupação da cidade 1: 45000
Digite a taxa de ocupação da cidade 2: 22000
Digite a taxa de ocupação da cidade 3: 11000
Dia 3
Digite a taxa de ocupação da cidade 1: 33000
Digite a taxa de ocupação da cidade 2: 17000
Digite a taxa de ocupação da cidade 3: 80000
Dia 4
Digite a taxa de ocupação da cidade 1: 24000
Digite a taxa de ocupação da cidade 2: 12000
Digite a taxa de ocupação da cidade 3: -80000
Dia 5
Digite a taxa de ocupação da cidade 1: 18000
Digite a taxa de ocupação da cidade 2: 9000
Digite a taxa de ocupação da cidade 3: 3000
Dia 6
Digite a taxa de ocupação da cidade 1: 7000
Digite a taxa de ocupação da cidade 2: 1000
Digite a taxa de ocupação da cidade 3: 333
Dia 7
Digite a taxa de ocupação da cidade 1: 1300
Digite a taxa de ocupação da cidade 2: 299
Digite a taxa de ocupação da cidade 3: -15
Cidade 1
Mínimo de ocup